# Generated by Django 4.0.3 on 2022-03-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='user',
            new_name='User',
        ),
    ]
