# Generated by Django 4.0.3 on 2022-03-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_employeedetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
