# Generated by Django 4.0.3 on 2022-03-12 08:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_rename_user_employeedetails_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeDetails',
            new_name='EmployeeDetail',
        ),
    ]
