# Generated by Django 4.0.3 on 2022-03-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_employeeleaves_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleaves',
            old_name='company1name',
            new_name='leaveType',
        ),
    ]
