# Generated by Django 4.0.3 on 2022-03-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_company1name_employeeleaves_leavetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleaves',
            name='company2name',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='yearofpassingpg',
        ),
        migrations.AddField(
            model_name='employeeleaves',
            name='fro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeeleaves',
            name='to',
            field=models.DateField(null=True),
        ),
    ]
