# Generated by Django 4.0.3 on 2022-03-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_employeeleaves_company2name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleaves',
            old_name='percentagegra',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='coursehsc',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='coursepggra',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='coursessc',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='percentagehsc',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='percentagepg',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='percentagessc',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='schoolclggra',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='schoolclghsc',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='schoolclgssc',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='yearofpassinghsc',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='yearofpassingra',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='yearofpassingssc',
        ),
    ]
