# Generated by Django 4.0.3 on 2022-03-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_coursehsc_employeeeducation_company1design_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company1design',
            new_name='coursehsc',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company1duration',
            new_name='coursepg',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company1name',
            new_name='coursepggra',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company1salary',
            new_name='coursessc',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company2design',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company2duration',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company2name',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company2salary',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company3design',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company3duration',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company3name',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company3salary',
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='percentagegra',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='percentagehsc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='percentagepg',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='percentagessc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='schoolclggra',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='schoolclghsc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='schoolclgpg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='schoolclgssc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='yearofpassinghsc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='yearofpassingpg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='yearofpassingra',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='yearofpassingssc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
