# Generated by Django 4.0.3 on 2022-03-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_company1design_employeeeducation_coursehsc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleaves',
            old_name='leaveType',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='employeeleaves',
            old_name='fro',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='to',
        ),
        migrations.RemoveField(
            model_name='employeeleaves',
            name='user',
        ),
        migrations.AddField(
            model_name='employeeleaves',
            name='age',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='employeeleaves',
            name='city',
            field=models.CharField(max_length=245, null=True),
        ),
        migrations.AddField(
            model_name='employeeleaves',
            name='email',
            field=models.CharField(max_length=233, null=True),
        ),
        migrations.AddField(
            model_name='employeeleaves',
            name='esalary',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeleaves',
            name='fname',
            field=models.CharField(max_length=233, null=True),
        ),
        migrations.AddField(
            model_name='employeeleaves',
            name='lname',
            field=models.CharField(max_length=233, null=True),
        ),
        migrations.AddField(
            model_name='employeeleaves',
            name='no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employeeleaves',
            name='osalary',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
