# Generated by Django 4.0.3 on 2022-03-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_date_employeeleaves_fro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeejob',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeejob',
            name='user',
        ),
    ]
