# Generated by Django 4.0.3 on 2022-03-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_employeejob_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeejob',
            name='user',
        ),
    ]
