# Generated by Django 2.0 on 2022-04-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220401_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperience',
            name='company1durationto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
