# Generated by Django 2.0 on 2022-04-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_employeeexperience_company1durationto'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperience',
            name='company2durationto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
