# Generated by Django 2.0 on 2022-04-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_employeeexperience_company2durationto'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperience',
            name='company3durationto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
