# Generated by Django 2.0 on 2022-04-06 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0024_employeeloan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeLoan',
            new_name='Loan',
        ),
    ]
