# Generated by Django 2.0 on 2022-04-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20220406_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
