# Generated by Django 2.0 on 2022-04-07 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0026_loan_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsalary', models.CharField(max_length=100, null=True)),
                ('HRA', models.CharField(max_length=100, null=True)),
                ('PF', models.CharField(max_length=100, null=True)),
                ('OT', models.CharField(max_length=100, null=True)),
                ('sat', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
