# Generated by Django 2.0 on 2022-04-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_esalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='esalary',
            name='sata',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
