# Generated by Django 2.0 on 2022-04-19 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0029_auto_20220419_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esalarye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs', models.CharField(max_length=100, null=True)),
                ('hra', models.CharField(max_length=100, null=True)),
                ('pf', models.CharField(max_length=100, null=True)),
                ('ot', models.CharField(max_length=100, null=True)),
                ('at', models.DateField(null=True)),
                ('am', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='esalary',
            name='user',
        ),
        migrations.DeleteModel(
            name='Esalary',
        ),
    ]
