# Generated by Django 2.0 on 2022-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20220420_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esalarye',
            name='am',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='esalarye',
            name='at',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
