# Generated by Django 2.0 on 2022-04-20 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220420_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esalarye',
            name='id',
        ),
        migrations.AlterField(
            model_name='esalarye',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
